---
title: Your awesome title
email: your-email@domain.com
description: description
baseurl: "/Jekyll-Avalon"
url: http://joshuaavalon.github.io
twitter_username: joshuaavalon
github_username: joshuaavalon
sass:
  style: compressed
paginate: 12
paginate_path: "/:num/"
author_img_s: "/img/author_s.png"
author_img: "/img/author.png"
navigation:
- text: Home
  url: "/"
- text: Categories
  url: "/categories.html"
- text: Tags
  url: "/tags.html"
read_more: Read More
env: production
minify_html: false
markdown: kramdown
sticky: sticky
sticky_count: 3
gems:
- jekyll-paginate
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
timezone: Asia/Shanghai
